title: bocom_credit
defaultCurrency: CNY
defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCashAccount: Liabilities:BOCOM:CreditCard
bocom_credit:
  rules:
    - item: 信用卡还款
      targetAccount: Equity:Transfers
    - item: 美团,饿了么
      targetAccount: Expenses:Food
